src/Web/TravelBookingPortal.Web/Controllers/CompaniesController.cs
namespace TravelBookingPortal.Web.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using TravelBookingPortal.Services.Data;
    using TravelBookingPortal.Web.ViewModels.Companies;

    public class CompaniesController : BaseController
    {
        private readonly ICompaniesService companiesService;

        public CompaniesController(ICompaniesService companiesService)
        {
            this.companiesService = companiesService;
        }

        public IActionResult ByName(string name)
        {
            var viewModel = this.companiesService.GetByName<CompanyViewModel>(name);
            return this.View(viewModel);
        }

        public IActionResult ById(int id)
        {
            var postViewModel = this.companiesService.GetById<CompanyViewModel>(id);
            if (postViewModel == null)
            {
                return this.NotFound();
            }

            return this.View(postViewModel);
        }
    }
}

src/Web/TravelBookingPortal.Web/Controllers/ToursController.cs
namespace TravelBookingPortal.Web.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using TravelBookingPortal.Services.Data;
    using TravelBookingPortal.Web.ViewModels.Tours;

    public class ToursController : BaseController
    {
        private readonly ICompaniesService companiesService;
        private readonly IToursService toursService;

        public ToursController(ICompaniesService companiesService, IToursService toursService)
        {
            this.companiesService = companiesService;
            this.toursService = toursService;
        }

        public IActionResult All()
        {
            var viewModel = new AllToursViewModel();

            var tours = this.toursService.GetAll<TourViewModel>();
            viewModel.Tours = tours;

            return this.View(viewModel);
        }

        public IActionResult ById(int id)
        {
            var postViewModel = this.toursService.GetById<TourDetailsViewModel>(id);
            if (postViewModel == null)
            {
                return this.NotFound();
            }

            return this.View(postViewModel);
        }
        //public IActionResult Details(int id)
        //{
        //    var postViewModel = this.toursService.GetById<TourDetailsViewModel>(id);
        //    if (postViewModel == null)
        //    {
        //        return this.NotFound();
        //    }

        //    return this.View(postViewModel);
        //}

    }
}

src/Web/TravelBookingPortal.Web/Views/Tours/All.cshtml
@using TravelBookingPortal.Common
@model TravelBookingPortal.Web.ViewModels.Tours.AllToursViewModel
@{ this.ViewData["Title"] = $"Welcome to {@GlobalConstants.SystemName}!"; }


<div class="text-center">
    <h1 class="display-4">@this.ViewData["Title"]</h1>
</div>



<p>&nbsp;</p>
<h3>All Tours</h3>


<div class="row">
    @foreach (var tour in Model.Tours)
    {
    <div class="col-md-4 media">
        <div class="card">
            <img src="@tour.Image" class="card-img-top" alt="@tour.Name">
            <div class="card-body">
                <h5 class="card-title">@tour.Name</h5>
                <p class="card-text">@tour.Duration days</p>
                <p class="card-text">From US$@tour.PriceTotal</p>
                @*<a href="/Tours/Details?tourId=@tour.Id" class="btn btn-info text-uppercase">LEARN MORE</a>*@
                <h6 class="media-heading"><a asp-controller="Tours" asp-action="ById" asp-route-id="@tour.Id">LEARN MORE</a></h6>
            </div>
        </div>
    </div>
    }
</div>

         

src/Web/TravelBookingPortal.Web/Views/Tours/ById.cshtml
@using TravelBookingPortal.Common
@model TravelBookingPortal.Web.ViewModels.Tours.TourDetailsViewModel
@{ this.ViewData["Title"] = $"Welcome to {@GlobalConstants.SystemName}!"; }

<section class="py-5">
    <div class="container">
        <h1 style="margin: 2%; text-align: center;">@Model.Name</h1>
        <h7>
            Best price guaranteed             No booking fees
        </h7>
        <div>
            <div class="form-group text-center">
                <img src="@Model.Image" class="img-fluid">
            </div>

            <div>
                <h6 class="mt-0">From US$ @Model.PriceTotal</h6>
            </div>
            <div>
                <h6 class="mt-0">DepartureDate: @Model.DepartureDate.ToString("d")</h6>
            </div>
            <div>
                <h6 class="mt-0">DepartureDate: @Model.ReturnDate.ToString("d")</h6>
            </div>
            <div>
                <h6 class="mt-0">Highlights</h6>
                @Model.Highlights
            </div>
            <div>
                <h6 class="mt-0">Included</h6>
                @Model.Included
            </div>
            <div>
                <h6 class="media-heading"><a asp-controller="Companies" asp-action="ById" asp-route-id="@Model.CompanyId">@Model.CompanyName</a></h6>
                <img src="@Model.CompanyLogo" width="80" class="mr-3" alt="@Model.CompanyName">
            </div>



            <div class="form-group text-center">
                <div class="button-holder">
                    <a href="/Trips/AddUserToTrip?tripId=@Model.Id" class="btn btn-primary btn-block text-uppercase">Book Now</a>
                </div>
            </div>
        </div>
    </div>
</section>